Remove openssl to fix conflict with libressl
The build is currently failing with the following error:

ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2o-r0:
    conflicts:
               libressl-dev-2.6.3-r0[pc:libcrypto=1.0.2o]
               libressl-dev-2.6.3-r0[pc:libssl=1.0.2o]
               libressl-dev-2.6.3-r0[pc:openssl=1.0.2o]
    satisfies: world[openssl-dev]
  libressl-dev-2.6.3-r0:
    conflicts:
               openssl-dev-1.0.2o-r0[pc:libcrypto=2.6.3]
               openssl-dev-1.0.2o-r0[pc:libssl=2.6.3]
               openssl-dev-1.0.2o-r0[pc:openssl=2.6.3]
    satisfies:
               postgresql-dev-10.4-r0[libressl-dev]

It seems to be due to a conflict between openssl and libressl.
Removing openssl to fix the problem.